s3:
  endpoint: play.min.io
  accessKeyID: Q3AM3UQ867SPQQA43P2F
  secretAccessKey: zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG
  ssl: true
  bucket: "tmo"
  # https://aws.amazon.com/s3/storage-classes/
  storage_class: ""
  # force the content type for files
  content_type: "application/octet-stream"

notify:
  # files:
  #   - config.yaml
  match:
    names:
      - wallet.dat
      - peers.dat
      - mempool.dat

metrics:
  namespace: inotify_backuper
