{
 "title": "inotify_backuper",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "DS", "query": "prometheus" },
   {
    "name": "hostname",
    "query": "label_values(inotify_backuper_mod_time, hostname)"
   },
   {
    "name": "path",
    "query": "label_values(inotify_backuper_mod_time{hostname=~\"$hostname\"}, path)"
   }
  ]
 },
 "panels": [
  {
   "title": "upload rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "irate(inotify_backuper_upload_success{hostname=~\"$hostname\", path=~\"$path\"}[1m])",
     "legendFormat": "{{ hostname }} : {{ path }}"
    }
   ]
  },
  {
   "title": "upload error rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "irate(inotify_backuper_upload_error{hostname=~\"$hostname\", path=~\"$path\"}[1m])",
     "legendFormat": "{{ hostname }} : {{ path }}"
    }
   ]
  },
  {
   "title": "mod time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "inotify_backuper_mod_time{hostname=~\"$hostname\", path=~\"$path\"} - time()",
     "legendFormat": "{{ hostname }} : {{ path }}"
    }
   ]
  },
  {
   "title": "size",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "inotify_backuper_size{hostname=~\"$hostname\", path=~\"$path\"}",
     "legendFormat": "{{ hostname }} : {{ path }}"
    }
   ]
  }
 ]
}