apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "inotify-backuper.fullname" . }}
  labels:
    {{- include "inotify-backuper.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "inotify-backuper.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/imagePullSecret.yaml: {{ include (print $.Template.BasePath "/imagePullSecret.yaml") . | sha256sum }}
        checksum/configmap.yaml: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        prometheus.io/port: "9119"
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "inotify-backuper.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "inotify-backuper.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: HOSTNAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: GOMAXPROCS
              valueFrom:
                resourceFieldRef:
                  containerName: {{ .Chart.Name }}
                  resource: limits.cpu
          command:
            - /go/bin/inotify-backuper
            - -in-cluster
            - -rootfs=/host
            - -listen-addr=0.0.0.0:9119
            - -config=/config.yaml
          ports:
            - name: http
              containerPort: 9119
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /metrics
              port: http
          readinessProbe:
            httpGet:
              path: /metrics
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - mountPath: /host
              name: rootfs
              readOnly: true
            - mountPath: /etc/ssl/certs/ca-certificates.crt
              name: ssl
              readOnly: true
            - name: config
              mountPath: /config.yaml
              subPath: config.yaml
              readOnly: true
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - hostPath:
            path: /
            type: ""
          name: rootfs
        - hostPath:
            path: /etc/ssl/certs/ca-certificates.crt
            type: "File"
          name: ssl
        - name: config
          configMap:
            name: {{ include "inotify-backuper.fullname" . }}
            defaultMode: 0777
            items:
              - key: config.yaml
                path: config.yaml

